
FROM imbios/bun-node:1.1.27-20.17.0-alpine AS base

FROM base AS deps
WORKDIR /app
# Check for lockfile and copy available one
COPY package.json bun.lock ./
# Install dependencies with cache
RUN --mount=type=cache,target=/root/.bun/install/cache \
  bun install --frozen-lockfile

FROM base AS runner
WORKDIR /app
COPY --from=deps /app/node_modules ./node_modules
COPY . .

# Environment for Dev
ENV NODE_ENV development
ENV NEXT_TELEMETRY_DISABLED 1

EXPOSE 3000

# Start dev server
CMD ["bun", "run", "dev", "--hostname", "0.0.0.0"]
