-- Auto-generated migration candidate: fix-uuid-columns.sql
-- Run only after reviewing and backing up your database.
-- Generated by scripts/generate-uuid-alter.js



BEGIN;

-- Casting appointments.user_id to uuid
ALTER TABLE "appointments" ALTER COLUMN "user_id" TYPE uuid USING ("user_id")::uuid;

-- Casting cart.session_id to uuid
ALTER TABLE "cart" ALTER COLUMN "session_id" TYPE uuid USING ("session_id")::uuid;

COMMIT;
